name: stochastic_process_inference
channels:
  - conda-forge
dependencies:
  - fenics
  - muq
  - scipy
  - sympy
  - matplotlib
  - seaborn
  - statsmodels
  - jupyter
  - pre-commit
  - pytest
  - h5py
