name: Main
run-name: Continuous Integration for main branch

# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

# -- Concurrency -----------------------------------------------------------------------------------
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  # Format code with Ruff (checks for failure)
  format:
    runs-on: ubuntu-latest
    if: ${{
      github.event_name == 'workflow_dispatch'||
      github.event_name == 'push' ||
      github.event.pull_request.merged == true
      }}
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Format with ruff
        id: format-with-ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format"

  #Build documentation without deploying
  docs:
    runs-on: ubuntu-latest
    if: ${{
      github.event_name == 'workflow_dispatch'||
      github.event_name == 'push' ||
      github.event.pull_request.merged == true
      }}
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Install Pixi
        id: setup-pixi
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          cache: true
      - name: Install dependencies
        id: install-deps
        run: pixi install -e docs
      - name: Build MkDocs documentation
        id: build-docs
        run: pixi run -e docs build-docs
